name: Continuous Integration
on:
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:  # ✅ Corrected from 'setps' to 'steps'
      - name: Check out repository code
        uses: actions/checkout@v4

      - name: Run Nullify vulnerability scanner
        uses: nullify-platform/dast-action@main
      