name: End-to-end tests
on: push
jobs:
  cypress-run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Cypress.io
        uses: cypress-io/github-action@v6.7.16
        with:
          runTests: true